@startuml
start

partition 随机与艺人见面的剧情 {
    :根据艺人性格进行筛选;
    :根据当前好感度进行筛选;
}
:播放见面剧情;

partition 随机供选择的饮料 {
    :随机三种饮料类型;
    note
    如：碳酸饮料、调制酒
    end note

    :随机上述三种类型对应的饮料名字;
    note
    对于碳酸类饮料
    玩家看得到可能是 <i>冰镇可乐</i>
    也可能是 <i>弹珠汽水</i> 或者 <i>黑松沙士</i>
    end note
}
:玩家选择给艺人点什么饮料;

partition 根据玩家选择随机艺人的反应 {
    :根据艺人性格进行筛选;
    :根据艺人对该类型饮料进行筛选;
    note
    艺人的反应取决于饮料的类型
    实际上与具体喝什么无关
    end note

    :带权随机出一段后续剧情;
    note
    每段后续剧情有独立的概率
    end note
}
:播放艺人的反应及后续剧情;

stop
@enduml