@startuml
start

:获取酒吧见面剧情库;
:检查触发条件;
:随机出一条剧情线;

repeat

partition 获取分支信息 {
    :读取分支信息;
    note
        仅负责剧情走向
        每个分支代表一段线性剧情片段，
        同时指向后续的剧情
        如果有多段后续剧情，
        将作为选项供玩家进行选择
    end note

    while (需要其他分支的信息?)
    note
    <img src=Options.jpg/>
        饮料选项就是通过合并
        随机出来的饮料类型与饮料名目合并而来
    end note
        :获取其他分支的信息;
        :合并信息;
    end while
}

partition 获取节点信息 {
    :获取节点信息;
    note
        只负责一句对话的所有展示信息
        不需要考虑剧情走向
    end note

    :替换占位符;
}

partition 获取后续分支 {
    :获取后续分支;
    :检查是否满足触发条件;
    :替换选项文字占位符;
}

:将所有信息组合成"对话"信息;
:播放对话;
:玩家点击下一步或者选择某个选项;

if (剧情已经结束) then (是)
    stop
endif

if (分支已结束) then (是)
    :跳转到选择的剧情分支;
endif

repeat while(true);

@enduml